//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace TestLLBL.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal partial class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitAccountEntityMappings();
			InitPetitionEntityMappings();
			InitPetitionStatusEntityMappings();
			InitPlanEntityMappings();
			InitPlanDetailEntityMappings();
			InitProjectEntityMappings();
			InitRatingTypeEntityMappings();
			InitTaskEntityMappings();
			InitTaskStatusEntityMappings();
			InitTaskTypeEntityMappings();
			InitUnitEntityMappings();
			InitUnitAndAccountEntityMappings();
			InitUnitTypeEntityMappings();
		}

		/// <summary>Inits AccountEntity's mappings</summary>
		private void InitAccountEntityMappings()
		{
			this.AddElementMapping("AccountEntity", @"QuanLyDuAn_DTPM", @"dbo", "Account", 7, 0);
			this.AddElementFieldMapping("AccountEntity", "Avatar", "Avatar", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("AccountEntity", "CreatedDate", "CreatedDate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("AccountEntity", "DisplayName", "DisplayName", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("AccountEntity", "Email", "Email", true, "VarChar", 200, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("AccountEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 4);
			this.AddElementFieldMapping("AccountEntity", "Password", "Password", true, "VarChar", 200, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("AccountEntity", "Username", "Username", true, "VarChar", 200, 0, 0, false, "", null, typeof(System.String), 6);
		}

		/// <summary>Inits PetitionEntity's mappings</summary>
		private void InitPetitionEntityMappings()
		{
			this.AddElementMapping("PetitionEntity", @"QuanLyDuAn_DTPM", @"dbo", "Petition", 6, 0);
			this.AddElementFieldMapping("PetitionEntity", "AccountId", "AccountId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("PetitionEntity", "Content", "Content", true, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("PetitionEntity", "CreatedDate", "CreatedDate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 2);
			this.AddElementFieldMapping("PetitionEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 3);
			this.AddElementFieldMapping("PetitionEntity", "PetitionStatusId", "PetitionStatusId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 4);
			this.AddElementFieldMapping("PetitionEntity", "Title", "Title", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 5);
		}

		/// <summary>Inits PetitionStatusEntity's mappings</summary>
		private void InitPetitionStatusEntityMappings()
		{
			this.AddElementMapping("PetitionStatusEntity", @"QuanLyDuAn_DTPM", @"dbo", "PetitionStatus", 2, 0);
			this.AddElementFieldMapping("PetitionStatusEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("PetitionStatusEntity", "Name", "Name", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits PlanEntity's mappings</summary>
		private void InitPlanEntityMappings()
		{
			this.AddElementMapping("PlanEntity", @"QuanLyDuAn_DTPM", @"dbo", "Plan1", 5, 0);
			this.AddElementFieldMapping("PlanEntity", "CreatedDate", "CreatedDate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("PlanEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("PlanEntity", "Name", "Name", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("PlanEntity", "ProjectId", "ProjectId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
			this.AddElementFieldMapping("PlanEntity", "UpdatedDate", "UpdatedDate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 4);
		}

		/// <summary>Inits PlanDetailEntity's mappings</summary>
		private void InitPlanDetailEntityMappings()
		{
			this.AddElementMapping("PlanDetailEntity", @"QuanLyDuAn_DTPM", @"dbo", "PlanDetail", 6, 0);
			this.AddElementFieldMapping("PlanDetailEntity", "CompleteDate", "CompleteDate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("PlanDetailEntity", "CreatedDate", "CreatedDate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("PlanDetailEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("PlanDetailEntity", "Name", "Name", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("PlanDetailEntity", "PlanId", "PlanId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 4);
			this.AddElementFieldMapping("PlanDetailEntity", "UpdatedDate", "UpdatedDate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 5);
		}

		/// <summary>Inits ProjectEntity's mappings</summary>
		private void InitProjectEntityMappings()
		{
			this.AddElementMapping("ProjectEntity", @"QuanLyDuAn_DTPM", @"dbo", "Project", 5, 0);
			this.AddElementFieldMapping("ProjectEntity", "AccountId", "AccountId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("ProjectEntity", "CreatedDate", "CreatedDate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("ProjectEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("ProjectEntity", "Name", "Name", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("ProjectEntity", "UpdatedDate", "UpdatedDate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 4);
		}

		/// <summary>Inits RatingTypeEntity's mappings</summary>
		private void InitRatingTypeEntityMappings()
		{
			this.AddElementMapping("RatingTypeEntity", @"QuanLyDuAn_DTPM", @"dbo", "RatingType", 2, 0);
			this.AddElementFieldMapping("RatingTypeEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("RatingTypeEntity", "Name", "Name", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits TaskEntity's mappings</summary>
		private void InitTaskEntityMappings()
		{
			this.AddElementMapping("TaskEntity", @"QuanLyDuAn_DTPM", @"dbo", "Task", 10, 0);
			this.AddElementFieldMapping("TaskEntity", "AccountId", "AccountId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("TaskEntity", "CreatedDate", "CreatedDate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("TaskEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("TaskEntity", "Name", "Name", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("TaskEntity", "PlanDetailId", "PlanDetailId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 4);
			this.AddElementFieldMapping("TaskEntity", "Progress", "Progress", true, "Float", 0, 38, 0, false, "", null, typeof(System.Double), 5);
			this.AddElementFieldMapping("TaskEntity", "RatingTypeId", "RatingTypeId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 6);
			this.AddElementFieldMapping("TaskEntity", "TaskStatusId", "TaskStatusId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 7);
			this.AddElementFieldMapping("TaskEntity", "TaskTypeId", "TaskTypeId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 8);
			this.AddElementFieldMapping("TaskEntity", "UpdatedDate", "UpdatedDate", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 9);
		}

		/// <summary>Inits TaskStatusEntity's mappings</summary>
		private void InitTaskStatusEntityMappings()
		{
			this.AddElementMapping("TaskStatusEntity", @"QuanLyDuAn_DTPM", @"dbo", "TaskStatus", 2, 0);
			this.AddElementFieldMapping("TaskStatusEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("TaskStatusEntity", "Name", "Name", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits TaskTypeEntity's mappings</summary>
		private void InitTaskTypeEntityMappings()
		{
			this.AddElementMapping("TaskTypeEntity", @"QuanLyDuAn_DTPM", @"dbo", "TaskType", 2, 0);
			this.AddElementFieldMapping("TaskTypeEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("TaskTypeEntity", "Name", "Name", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits UnitEntity's mappings</summary>
		private void InitUnitEntityMappings()
		{
			this.AddElementMapping("UnitEntity", @"QuanLyDuAn_DTPM", @"dbo", "Unit", 3, 0);
			this.AddElementFieldMapping("UnitEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("UnitEntity", "Name", "Name", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("UnitEntity", "UnitTypeId", "UnitTypeId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
		}

		/// <summary>Inits UnitAndAccountEntity's mappings</summary>
		private void InitUnitAndAccountEntityMappings()
		{
			this.AddElementMapping("UnitAndAccountEntity", @"QuanLyDuAn_DTPM", @"dbo", "UnitAndAccount", 3, 0);
			this.AddElementFieldMapping("UnitAndAccountEntity", "AccountId", "AccountId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("UnitAndAccountEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("UnitAndAccountEntity", "UnitId", "UnitId", true, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
		}

		/// <summary>Inits UnitTypeEntity's mappings</summary>
		private void InitUnitTypeEntityMappings()
		{
			this.AddElementMapping("UnitTypeEntity", @"QuanLyDuAn_DTPM", @"dbo", "UnitType", 2, 0);
			this.AddElementFieldMapping("UnitTypeEntity", "Id", "Id", false, "Int", 0, 10, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("UnitTypeEntity", "Name", "Name", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 1);
		}

	}
}
