//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace TestLLBL.HelperClasses
{
	/// <summary>Field Creation Class for entity AccountEntity</summary>
	public partial class AccountFields
	{
		/// <summary>Creates a new AccountEntity.Avatar field instance</summary>
		public static EntityField2 Avatar { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AccountFieldIndex.Avatar); }}
		/// <summary>Creates a new AccountEntity.CreatedDate field instance</summary>
		public static EntityField2 CreatedDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AccountFieldIndex.CreatedDate); }}
		/// <summary>Creates a new AccountEntity.DisplayName field instance</summary>
		public static EntityField2 DisplayName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AccountFieldIndex.DisplayName); }}
		/// <summary>Creates a new AccountEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AccountFieldIndex.Email); }}
		/// <summary>Creates a new AccountEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AccountFieldIndex.Id); }}
		/// <summary>Creates a new AccountEntity.Password field instance</summary>
		public static EntityField2 Password { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AccountFieldIndex.Password); }}
		/// <summary>Creates a new AccountEntity.Username field instance</summary>
		public static EntityField2 Username { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AccountFieldIndex.Username); }}
	}

	/// <summary>Field Creation Class for entity PetitionEntity</summary>
	public partial class PetitionFields
	{
		/// <summary>Creates a new PetitionEntity.AccountId field instance</summary>
		public static EntityField2 AccountId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PetitionFieldIndex.AccountId); }}
		/// <summary>Creates a new PetitionEntity.Content field instance</summary>
		public static EntityField2 Content { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PetitionFieldIndex.Content); }}
		/// <summary>Creates a new PetitionEntity.CreatedDate field instance</summary>
		public static EntityField2 CreatedDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PetitionFieldIndex.CreatedDate); }}
		/// <summary>Creates a new PetitionEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PetitionFieldIndex.Id); }}
		/// <summary>Creates a new PetitionEntity.PetitionStatusId field instance</summary>
		public static EntityField2 PetitionStatusId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PetitionFieldIndex.PetitionStatusId); }}
		/// <summary>Creates a new PetitionEntity.Title field instance</summary>
		public static EntityField2 Title { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PetitionFieldIndex.Title); }}
	}

	/// <summary>Field Creation Class for entity PetitionStatusEntity</summary>
	public partial class PetitionStatusFields
	{
		/// <summary>Creates a new PetitionStatusEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PetitionStatusFieldIndex.Id); }}
		/// <summary>Creates a new PetitionStatusEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PetitionStatusFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity PlanEntity</summary>
	public partial class PlanFields
	{
		/// <summary>Creates a new PlanEntity.CreatedDate field instance</summary>
		public static EntityField2 CreatedDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanFieldIndex.CreatedDate); }}
		/// <summary>Creates a new PlanEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanFieldIndex.Id); }}
		/// <summary>Creates a new PlanEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanFieldIndex.Name); }}
		/// <summary>Creates a new PlanEntity.ProjectId field instance</summary>
		public static EntityField2 ProjectId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanFieldIndex.ProjectId); }}
		/// <summary>Creates a new PlanEntity.UpdatedDate field instance</summary>
		public static EntityField2 UpdatedDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanFieldIndex.UpdatedDate); }}
	}

	/// <summary>Field Creation Class for entity PlanDetailEntity</summary>
	public partial class PlanDetailFields
	{
		/// <summary>Creates a new PlanDetailEntity.CompleteDate field instance</summary>
		public static EntityField2 CompleteDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanDetailFieldIndex.CompleteDate); }}
		/// <summary>Creates a new PlanDetailEntity.CreatedDate field instance</summary>
		public static EntityField2 CreatedDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanDetailFieldIndex.CreatedDate); }}
		/// <summary>Creates a new PlanDetailEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanDetailFieldIndex.Id); }}
		/// <summary>Creates a new PlanDetailEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanDetailFieldIndex.Name); }}
		/// <summary>Creates a new PlanDetailEntity.PlanId field instance</summary>
		public static EntityField2 PlanId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanDetailFieldIndex.PlanId); }}
		/// <summary>Creates a new PlanDetailEntity.UpdatedDate field instance</summary>
		public static EntityField2 UpdatedDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PlanDetailFieldIndex.UpdatedDate); }}
	}

	/// <summary>Field Creation Class for entity ProjectEntity</summary>
	public partial class ProjectFields
	{
		/// <summary>Creates a new ProjectEntity.AccountId field instance</summary>
		public static EntityField2 AccountId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.AccountId); }}
		/// <summary>Creates a new ProjectEntity.CreatedDate field instance</summary>
		public static EntityField2 CreatedDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.CreatedDate); }}
		/// <summary>Creates a new ProjectEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.Id); }}
		/// <summary>Creates a new ProjectEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.Name); }}
		/// <summary>Creates a new ProjectEntity.UpdatedDate field instance</summary>
		public static EntityField2 UpdatedDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.UpdatedDate); }}
	}

	/// <summary>Field Creation Class for entity RatingTypeEntity</summary>
	public partial class RatingTypeFields
	{
		/// <summary>Creates a new RatingTypeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RatingTypeFieldIndex.Id); }}
		/// <summary>Creates a new RatingTypeEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RatingTypeFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity TaskEntity</summary>
	public partial class TaskFields
	{
		/// <summary>Creates a new TaskEntity.AccountId field instance</summary>
		public static EntityField2 AccountId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TaskFieldIndex.AccountId); }}
		/// <summary>Creates a new TaskEntity.CreatedDate field instance</summary>
		public static EntityField2 CreatedDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TaskFieldIndex.CreatedDate); }}
		/// <summary>Creates a new TaskEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TaskFieldIndex.Id); }}
		/// <summary>Creates a new TaskEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TaskFieldIndex.Name); }}
		/// <summary>Creates a new TaskEntity.PlanDetailId field instance</summary>
		public static EntityField2 PlanDetailId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TaskFieldIndex.PlanDetailId); }}
		/// <summary>Creates a new TaskEntity.Progress field instance</summary>
		public static EntityField2 Progress { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TaskFieldIndex.Progress); }}
		/// <summary>Creates a new TaskEntity.RatingTypeId field instance</summary>
		public static EntityField2 RatingTypeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TaskFieldIndex.RatingTypeId); }}
		/// <summary>Creates a new TaskEntity.TaskStatusId field instance</summary>
		public static EntityField2 TaskStatusId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TaskFieldIndex.TaskStatusId); }}
		/// <summary>Creates a new TaskEntity.TaskTypeId field instance</summary>
		public static EntityField2 TaskTypeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TaskFieldIndex.TaskTypeId); }}
		/// <summary>Creates a new TaskEntity.UpdatedDate field instance</summary>
		public static EntityField2 UpdatedDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TaskFieldIndex.UpdatedDate); }}
	}

	/// <summary>Field Creation Class for entity TaskStatusEntity</summary>
	public partial class TaskStatusFields
	{
		/// <summary>Creates a new TaskStatusEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TaskStatusFieldIndex.Id); }}
		/// <summary>Creates a new TaskStatusEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TaskStatusFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity TaskTypeEntity</summary>
	public partial class TaskTypeFields
	{
		/// <summary>Creates a new TaskTypeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TaskTypeFieldIndex.Id); }}
		/// <summary>Creates a new TaskTypeEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TaskTypeFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity UnitEntity</summary>
	public partial class UnitFields
	{
		/// <summary>Creates a new UnitEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.Id); }}
		/// <summary>Creates a new UnitEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.Name); }}
		/// <summary>Creates a new UnitEntity.UnitTypeId field instance</summary>
		public static EntityField2 UnitTypeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.UnitTypeId); }}
	}

	/// <summary>Field Creation Class for entity UnitAndAccountEntity</summary>
	public partial class UnitAndAccountFields
	{
		/// <summary>Creates a new UnitAndAccountEntity.AccountId field instance</summary>
		public static EntityField2 AccountId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitAndAccountFieldIndex.AccountId); }}
		/// <summary>Creates a new UnitAndAccountEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitAndAccountFieldIndex.Id); }}
		/// <summary>Creates a new UnitAndAccountEntity.UnitId field instance</summary>
		public static EntityField2 UnitId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitAndAccountFieldIndex.UnitId); }}
	}

	/// <summary>Field Creation Class for entity UnitTypeEntity</summary>
	public partial class UnitTypeFields
	{
		/// <summary>Creates a new UnitTypeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitTypeFieldIndex.Id); }}
		/// <summary>Creates a new UnitTypeEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitTypeFieldIndex.Name); }}
	}
	

}