//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
////////////////////////////////////////////////////////////// 
using System;
using System.Linq;
using TestLLBL.EntityClasses;
using TestLLBL.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec.AdapterSpecific;
using SD.LLBLGen.Pro.QuerySpec;

namespace TestLLBL.FactoryClasses
{
	/// <summary>Factory class to produce DynamicQuery instances and EntityQuery instances</summary>
	public partial class QueryFactory : QueryFactoryBase2
	{
		/// <summary>Creates and returns a new EntityQuery for the Account entity</summary>
		public EntityQuery<AccountEntity> Account { get { return Create<AccountEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Petition entity</summary>
		public EntityQuery<PetitionEntity> Petition { get { return Create<PetitionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the PetitionStatus entity</summary>
		public EntityQuery<PetitionStatusEntity> PetitionStatus { get { return Create<PetitionStatusEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Plan entity</summary>
		public EntityQuery<PlanEntity> Plan { get { return Create<PlanEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the PlanDetail entity</summary>
		public EntityQuery<PlanDetailEntity> PlanDetail { get { return Create<PlanDetailEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Project entity</summary>
		public EntityQuery<ProjectEntity> Project { get { return Create<ProjectEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the RatingType entity</summary>
		public EntityQuery<RatingTypeEntity> RatingType { get { return Create<RatingTypeEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Task entity</summary>
		public EntityQuery<TaskEntity> Task { get { return Create<TaskEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the TaskStatus entity</summary>
		public EntityQuery<TaskStatusEntity> TaskStatus { get { return Create<TaskStatusEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the TaskType entity</summary>
		public EntityQuery<TaskTypeEntity> TaskType { get { return Create<TaskTypeEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Unit entity</summary>
		public EntityQuery<UnitEntity> Unit { get { return Create<UnitEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the UnitAndAccount entity</summary>
		public EntityQuery<UnitAndAccountEntity> UnitAndAccount { get { return Create<UnitAndAccountEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the UnitType entity</summary>
		public EntityQuery<UnitTypeEntity> UnitType { get { return Create<UnitTypeEntity>(); } }

		/// <inheritdoc/>
		protected override IElementCreatorCore CreateElementCreator() { return new ElementCreator(); }
 
	}
}