//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace TestLLBL
{


	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>Account</summary>
		AccountEntity,
		///<summary>Petition</summary>
		PetitionEntity,
		///<summary>PetitionStatus</summary>
		PetitionStatusEntity,
		///<summary>Plan</summary>
		PlanEntity,
		///<summary>PlanDetail</summary>
		PlanDetailEntity,
		///<summary>Project</summary>
		ProjectEntity,
		///<summary>RatingType</summary>
		RatingTypeEntity,
		///<summary>Task</summary>
		TaskEntity,
		///<summary>TaskStatus</summary>
		TaskStatusEntity,
		///<summary>TaskType</summary>
		TaskTypeEntity,
		///<summary>Unit</summary>
		UnitEntity,
		///<summary>UnitAndAccount</summary>
		UnitAndAccountEntity,
		///<summary>UnitType</summary>
		UnitTypeEntity
	}



	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END


}

