//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using TestLLBL.HelperClasses;
using TestLLBL.FactoryClasses;
using TestLLBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace TestLLBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'PetitionStatus'.<br/><br/></summary>
	[Serializable]
	public partial class PetitionStatusEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<PetitionEntity> _petitions;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static PetitionStatusEntityStaticMetaData _staticMetaData = new PetitionStatusEntityStaticMetaData();
		private static PetitionStatusRelations _relationsFactory = new PetitionStatusRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Petitions</summary>
			public static readonly string Petitions = "Petitions";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class PetitionStatusEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public PetitionStatusEntityStaticMetaData()
			{
				SetEntityCoreInfo("PetitionStatusEntity", InheritanceHierarchyType.None, false, (int)TestLLBL.EntityType.PetitionStatusEntity, typeof(PetitionStatusEntity), typeof(PetitionStatusEntityFactory), false);
				AddNavigatorMetaData<PetitionStatusEntity, EntityCollection<PetitionEntity>>("Petitions", a => a._petitions, (a, b) => a._petitions = b, a => a.Petitions, () => new PetitionStatusRelations().PetitionEntityUsingPetitionStatusId, typeof(PetitionEntity), (int)TestLLBL.EntityType.PetitionEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static PetitionStatusEntity()
		{
		}

		/// <summary> CTor</summary>
		public PetitionStatusEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public PetitionStatusEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this PetitionStatusEntity</param>
		public PetitionStatusEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for PetitionStatus which data should be fetched into this PetitionStatus object</param>
		public PetitionStatusEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for PetitionStatus which data should be fetched into this PetitionStatus object</param>
		/// <param name="validator">The custom validator object for this PetitionStatusEntity</param>
		public PetitionStatusEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected PetitionStatusEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Petition' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPetitions() { return CreateRelationInfoForNavigator("Petitions"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this PetitionStatusEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static PetitionStatusRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Petition' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPetitions { get { return _staticMetaData.GetPrefetchPathElement("Petitions", CommonEntityBase.CreateEntityCollection<PetitionEntity>()); } }

		/// <summary>The Id property of the Entity PetitionStatus<br/><br/></summary>
		/// <remarks>Mapped on  table field: "PetitionStatus"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)PetitionStatusFieldIndex.Id, true); }
			set { SetValue((int)PetitionStatusFieldIndex.Id, value); }
		}

		/// <summary>The Name property of the Entity PetitionStatus<br/><br/></summary>
		/// <remarks>Mapped on  table field: "PetitionStatus"."Name".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)PetitionStatusFieldIndex.Name, true); }
			set { SetValue((int)PetitionStatusFieldIndex.Name, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'PetitionEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(PetitionEntity))]
		public virtual EntityCollection<PetitionEntity> Petitions { get { return GetOrCreateEntityCollection<PetitionEntity, PetitionEntityFactory>("PetitionStatus", true, false, ref _petitions); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace TestLLBL
{
	public enum PetitionStatusFieldIndex
	{
		///<summary>Id. </summary>
		Id,
		///<summary>Name. </summary>
		Name,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace TestLLBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: PetitionStatus. </summary>
	public partial class PetitionStatusRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between PetitionStatusEntity and PetitionEntity over the 1:n relation they have, using the relation between the fields: PetitionStatus.Id - Petition.PetitionStatusId</summary>
		public virtual IEntityRelation PetitionEntityUsingPetitionStatusId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Petitions", true, new[] { PetitionStatusFields.Id, PetitionFields.PetitionStatusId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticPetitionStatusRelations
	{
		internal static readonly IEntityRelation PetitionEntityUsingPetitionStatusIdStatic = new PetitionStatusRelations().PetitionEntityUsingPetitionStatusId;

		/// <summary>CTor</summary>
		static StaticPetitionStatusRelations() { }
	}
}
