//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using TestLLBL.HelperClasses;
using TestLLBL.FactoryClasses;
using TestLLBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace TestLLBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'UnitType'.<br/><br/></summary>
	[Serializable]
	public partial class UnitTypeEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<UnitEntity> _units;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static UnitTypeEntityStaticMetaData _staticMetaData = new UnitTypeEntityStaticMetaData();
		private static UnitTypeRelations _relationsFactory = new UnitTypeRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Units</summary>
			public static readonly string Units = "Units";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class UnitTypeEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public UnitTypeEntityStaticMetaData()
			{
				SetEntityCoreInfo("UnitTypeEntity", InheritanceHierarchyType.None, false, (int)TestLLBL.EntityType.UnitTypeEntity, typeof(UnitTypeEntity), typeof(UnitTypeEntityFactory), false);
				AddNavigatorMetaData<UnitTypeEntity, EntityCollection<UnitEntity>>("Units", a => a._units, (a, b) => a._units = b, a => a.Units, () => new UnitTypeRelations().UnitEntityUsingUnitTypeId, typeof(UnitEntity), (int)TestLLBL.EntityType.UnitEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static UnitTypeEntity()
		{
		}

		/// <summary> CTor</summary>
		public UnitTypeEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public UnitTypeEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this UnitTypeEntity</param>
		public UnitTypeEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for UnitType which data should be fetched into this UnitType object</param>
		public UnitTypeEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for UnitType which data should be fetched into this UnitType object</param>
		/// <param name="validator">The custom validator object for this UnitTypeEntity</param>
		public UnitTypeEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected UnitTypeEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Unit' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUnits() { return CreateRelationInfoForNavigator("Units"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this UnitTypeEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static UnitTypeRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Unit' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUnits { get { return _staticMetaData.GetPrefetchPathElement("Units", CommonEntityBase.CreateEntityCollection<UnitEntity>()); } }

		/// <summary>The Id property of the Entity UnitType<br/><br/></summary>
		/// <remarks>Mapped on  table field: "UnitType"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)UnitTypeFieldIndex.Id, true); }
			set { SetValue((int)UnitTypeFieldIndex.Id, value); }
		}

		/// <summary>The Name property of the Entity UnitType<br/><br/></summary>
		/// <remarks>Mapped on  table field: "UnitType"."Name".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)UnitTypeFieldIndex.Name, true); }
			set { SetValue((int)UnitTypeFieldIndex.Name, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'UnitEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(UnitEntity))]
		public virtual EntityCollection<UnitEntity> Units { get { return GetOrCreateEntityCollection<UnitEntity, UnitEntityFactory>("UnitType", true, false, ref _units); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace TestLLBL
{
	public enum UnitTypeFieldIndex
	{
		///<summary>Id. </summary>
		Id,
		///<summary>Name. </summary>
		Name,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace TestLLBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: UnitType. </summary>
	public partial class UnitTypeRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between UnitTypeEntity and UnitEntity over the 1:n relation they have, using the relation between the fields: UnitType.Id - Unit.UnitTypeId</summary>
		public virtual IEntityRelation UnitEntityUsingUnitTypeId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Units", true, new[] { UnitTypeFields.Id, UnitFields.UnitTypeId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticUnitTypeRelations
	{
		internal static readonly IEntityRelation UnitEntityUsingUnitTypeIdStatic = new UnitTypeRelations().UnitEntityUsingUnitTypeId;

		/// <summary>CTor</summary>
		static StaticUnitTypeRelations() { }
	}
}
