//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using TestLLBL.HelperClasses;
using TestLLBL.FactoryClasses;
using TestLLBL.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace TestLLBL.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'UnitAndAccount'.<br/><br/></summary>
	[Serializable]
	public partial class UnitAndAccountEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private AccountEntity _account;
		private UnitEntity _unit;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static UnitAndAccountEntityStaticMetaData _staticMetaData = new UnitAndAccountEntityStaticMetaData();
		private static UnitAndAccountRelations _relationsFactory = new UnitAndAccountRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Account</summary>
			public static readonly string Account = "Account";
			/// <summary>Member name Unit</summary>
			public static readonly string Unit = "Unit";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class UnitAndAccountEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public UnitAndAccountEntityStaticMetaData()
			{
				SetEntityCoreInfo("UnitAndAccountEntity", InheritanceHierarchyType.None, false, (int)TestLLBL.EntityType.UnitAndAccountEntity, typeof(UnitAndAccountEntity), typeof(UnitAndAccountEntityFactory), false);
				AddNavigatorMetaData<UnitAndAccountEntity, AccountEntity>("Account", "UnitAndAccounts", (a, b) => a._account = b, a => a._account, (a, b) => a.Account = b, TestLLBL.RelationClasses.StaticUnitAndAccountRelations.AccountEntityUsingAccountIdStatic, ()=>new UnitAndAccountRelations().AccountEntityUsingAccountId, null, new int[] { (int)UnitAndAccountFieldIndex.AccountId }, null, true, (int)TestLLBL.EntityType.AccountEntity);
				AddNavigatorMetaData<UnitAndAccountEntity, UnitEntity>("Unit", "UnitAndAccounts", (a, b) => a._unit = b, a => a._unit, (a, b) => a.Unit = b, TestLLBL.RelationClasses.StaticUnitAndAccountRelations.UnitEntityUsingUnitIdStatic, ()=>new UnitAndAccountRelations().UnitEntityUsingUnitId, null, new int[] { (int)UnitAndAccountFieldIndex.UnitId }, null, true, (int)TestLLBL.EntityType.UnitEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static UnitAndAccountEntity()
		{
		}

		/// <summary> CTor</summary>
		public UnitAndAccountEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public UnitAndAccountEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this UnitAndAccountEntity</param>
		public UnitAndAccountEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for UnitAndAccount which data should be fetched into this UnitAndAccount object</param>
		public UnitAndAccountEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for UnitAndAccount which data should be fetched into this UnitAndAccount object</param>
		/// <param name="validator">The custom validator object for this UnitAndAccountEntity</param>
		public UnitAndAccountEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected UnitAndAccountEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Account' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAccount() { return CreateRelationInfoForNavigator("Account"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Unit' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUnit() { return CreateRelationInfoForNavigator("Unit"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this UnitAndAccountEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static UnitAndAccountRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Account' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAccount { get { return _staticMetaData.GetPrefetchPathElement("Account", CommonEntityBase.CreateEntityCollection<AccountEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Unit' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUnit { get { return _staticMetaData.GetPrefetchPathElement("Unit", CommonEntityBase.CreateEntityCollection<UnitEntity>()); } }

		/// <summary>The AccountId property of the Entity UnitAndAccount<br/><br/></summary>
		/// <remarks>Mapped on  table field: "UnitAndAccount"."AccountId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> AccountId
		{
			get { return (Nullable<System.Int32>)GetValue((int)UnitAndAccountFieldIndex.AccountId, false); }
			set { SetValue((int)UnitAndAccountFieldIndex.AccountId, value); }
		}

		/// <summary>The Id property of the Entity UnitAndAccount<br/><br/></summary>
		/// <remarks>Mapped on  table field: "UnitAndAccount"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)UnitAndAccountFieldIndex.Id, true); }
			set { SetValue((int)UnitAndAccountFieldIndex.Id, value); }
		}

		/// <summary>The UnitId property of the Entity UnitAndAccount<br/><br/></summary>
		/// <remarks>Mapped on  table field: "UnitAndAccount"."UnitId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> UnitId
		{
			get { return (Nullable<System.Int32>)GetValue((int)UnitAndAccountFieldIndex.UnitId, false); }
			set { SetValue((int)UnitAndAccountFieldIndex.UnitId, value); }
		}

		/// <summary>Gets / sets related entity of type 'AccountEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual AccountEntity Account
		{
			get { return _account; }
			set { SetSingleRelatedEntityNavigator(value, "Account"); }
		}

		/// <summary>Gets / sets related entity of type 'UnitEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UnitEntity Unit
		{
			get { return _unit; }
			set { SetSingleRelatedEntityNavigator(value, "Unit"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace TestLLBL
{
	public enum UnitAndAccountFieldIndex
	{
		///<summary>AccountId. </summary>
		AccountId,
		///<summary>Id. </summary>
		Id,
		///<summary>UnitId. </summary>
		UnitId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace TestLLBL.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: UnitAndAccount. </summary>
	public partial class UnitAndAccountRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between UnitAndAccountEntity and AccountEntity over the m:1 relation they have, using the relation between the fields: UnitAndAccount.AccountId - Account.Id</summary>
		public virtual IEntityRelation AccountEntityUsingAccountId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Account", false, new[] { AccountFields.Id, UnitAndAccountFields.AccountId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between UnitAndAccountEntity and UnitEntity over the m:1 relation they have, using the relation between the fields: UnitAndAccount.UnitId - Unit.Id</summary>
		public virtual IEntityRelation UnitEntityUsingUnitId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Unit", false, new[] { UnitFields.Id, UnitAndAccountFields.UnitId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticUnitAndAccountRelations
	{
		internal static readonly IEntityRelation AccountEntityUsingAccountIdStatic = new UnitAndAccountRelations().AccountEntityUsingAccountId;
		internal static readonly IEntityRelation UnitEntityUsingUnitIdStatic = new UnitAndAccountRelations().UnitEntityUsingUnitId;

		/// <summary>CTor</summary>
		static StaticUnitAndAccountRelations() { }
	}
}
